### PR TITLE
Callback on set date bugfix, general bugfix

### PR DESCRIPTION
**Pull request by keenondrums**

### CODE REVIEW

**Comment by keenondrums** [comment]
Fixed a new bug: 
it was impossible to pick August 31 from September view

**Comment by lcustodio** [comment]
Something seems odd here. Even though the release v1.0.20 seems to be merged into master. The list of release on git (and per consequence in bower) shows the latest as being 1.0.19 which still has a reference to lodash.  Can I help with something?

**Comment by keenondrums** [comment]
Well, I guess I had to commit my changes first first, and then increment the version. You live, you learn.  A new pull request with an updated version created.

**Comment by lcustodio** [comment]
Ahh cool, great. Thanks!

**Pull request merged**
