### PR TITLE
Feature -> Watch Direct Model Changes

### PR DESCRIPTION
**Pull request by keenondrums**
updates the date picker view if the model was updated in the parent scope

### CODE REVIEW

**Comment by eralha** [comment]
This PR have no documentation. Should be made a change to the readme file, including this attribute, so that every developer can see this behaviour.

**Comment by keenondrums** [comment]
Sorry. Added some documentation with the best explanation of a use-case I could come up with.

**Comment by eralha** [comment]
Still uncomplete, sorry, the build is missing. Use Grunt to build the changes made to the project.

**Comment by keenondrums** [comment]
My bad. Done!

**Comment by eralha** [comment]
Thanks

**Comment by keenondrums** [comment]
Would you be so kind to let me know when the new release is expected?

**Pull request merged**
