### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by astik**
fix test that were failing due to faulty hour management ...

### CODE REVIEW

**Comment by astik** [comment]
also, i added a travis configuration file =)

**Comment by astik** [comment]
And now there is a circleci config file.
Good news is : project's all green =)
Still, I'm no expert with circleci, so it may need some tuning =D

**Comment by eralha** [comment]
You forgot to run the build with grunt, can you do that and send a new PR?

**Comment by astik** [comment]
You're right, my bad.
I'll do it tonight (in 10 hours max) as I cannot do it from where I am right now.
In the meantime, thanks for having merge those requests =)

**Comment by eralha** [comment]
Shure! every contribution is welcome.

**Pull request merged**
