### PR TITLE
Added min and max validation to dateTime and datePicker directives

### PR DESCRIPTION
**Pull request by SuricateCan**
I wrote the function in the correct location and did the grunt build as requested by @eralha.

### CODE REVIEW

**Comment by eralha** [comment]
Is it working as intended? http://plnkr.co/edit/2mVdDodovYhJGILRPrAZ?p=preview my input field is updating and i have set the min value.

**Comment by eralha** [comment]
Ok i have read the note: (only validation was added...)

**Comment by SuricateCan** [comment]
@eralha Yeah, only validation. That was all I needed for my project, at least for now. If you implement the restraint though, that would be very nice.

**Comment by eralha** [comment]
it invalidate the ngModel, so i think that will be enough for most cases, if some one request the restraint feature i will implement it, for now its good as it is :) thanks for the colaboration!

**Comment by SuricateCan** [comment]
My pleasure!

**Pull request merged**
